---
- hosts: "{{ hosts }}"
  ignore_unreachable: true
  
  tasks:
   - name: update apt packages
     become: yes
     apt:
      upgrade: yes
      update_cache: yes
     ignore_errors: true
     
   - name: check if system reboot is required
     become: true
     stat:
       path: /var/run/reboot-required
     register: reboot_required
     ignore_errors: true
   - name: send discord message
     uri:
       url: "{{ discord_webhook_url }}"
       method: POST
       body_format: json
       body: '{"content": "Reboot Required on {{ inventory_hostname }}"}'
       headers:
         Content-Type: application/json
       status_code: 204
     when: reboot_required.stat.exists
     ignore_errors: true